stages:
  - build
  - deploy

default:
  image: python:3.11-bookworm
  cache:
    paths:
      - .cache/pip

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

build-package:
  stage: build
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' || ($CI_PIPELINE_SOURCE == 'push' && ($CI_COMMIT_REF_NAME == 'dev' || $CI_COMMIT_REF_NAME == 'main'))
      changes:
        - src/**/*
        - pyproject.toml
        - .gitlab-ci.yml
  script:
    - pip install build
    - python -m build .
  artifacts:
    paths:
      - dist/

publish-package:
  stage: deploy
  rules:
    - if: $CI_PIPELINE_SOURCE == 'push' && $CI_COMMIT_REF_NAME == 'main'
      changes:
        - src/**/*
        - pyproject.toml
        - .gitlab-ci.yml
  script:
    - pip install twine
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
