name: documentation

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build and publish documentation
    runs-on: ubuntu-latest
    fail-fast: false
    matrix:
      python-version: ["3.10"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python-version}}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install .[docs]

      - name: Build documentation
        working-directory: ./docs
        run: |
          sphinx-build ./source ./build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "docs/build/html"
  deploy:
    run-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Publish to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
